// Style reminder: profile is a compact customer account surface, with a clear staff handoff for kitchen-authorized users.

import { useEffect, useState } from "react";
import { ArrowRight, ChefHat, LogIn, LogOut, MapPin, PackageCheck, Save, UserRound } from "lucide-react";
import { useLocation } from "wouter";
import { toast } from "sonner";
import { startLogin } from "@/const";
import { useAuth } from "@/_core/hooks/useAuth";
import { formatGhsPesewas } from "@/lib/catalog-types";
import { trpc } from "@/lib/trpc";
import { setDemoSession } from "@/lib/demo-auth";
import { getKitchenProfileAccess } from "@/lib/kitchen-access";

export default function Account() {
  const { user, isAuthenticated, logout } = useAuth();
  const [, setLocation] = useLocation();
  const utils = trpc.useUtils();
  const profileQuery = trpc.storefront.profile.useQuery(undefined, { enabled: isAuthenticated, retry: false });
  const ordersQuery = trpc.storefront.orders.useQuery(undefined, { enabled: isAuthenticated, retry: false });
  const [phone, setPhone] = useState("");
  const [defaultAddress, setDefaultAddress] = useState("");
  const [username, setUsername] = useState("demo@crunchbite.local");
  const [password, setPassword] = useState("Crunch!2026");
  const kitchenAccess = getKitchenProfileAccess(user?.role);
  const saveMutation = trpc.storefront.saveProfile.useMutation({ onSuccess: async () => { await utils.storefront.profile.invalidate(); toast.success("Profile saved"); }, onError: (error) => toast.error("Couldn’t save profile", { description: error.message }) });
  const demoLoginMutation = trpc.demoAuth.login.useMutation({ onSuccess: async () => { setDemoSession(); await utils.auth.me.invalidate(); toast.success("Signed in with the development demo account"); }, onError: (error) => toast.error("Demo sign-in failed", { description: error.message }) });
  useEffect(() => { setPhone(profileQuery.data?.phone ?? ""); setDefaultAddress(profileQuery.data?.defaultAddress ?? ""); }, [profileQuery.data]);

  if (!isAuthenticated) return <div className="min-h-[calc(100vh-62px)] bg-[#0b0b0b] px-5 py-14 sm:px-8 md:min-h-screen md:px-12 md:py-24"><div className="mx-auto max-w-[620px]"><span className="flex h-14 w-14 items-center justify-center rounded-[14px] bg-[#ff5a1f] text-[#111111] shadow-[4px_4px_0_#000]"><UserRound size={25} /></span><p className="mt-10 text-[10px] font-black uppercase tracking-[0.18em] text-[#ff5a1f]">Your Crunch Bite account</p><h1 className="mt-2 font-display text-[clamp(2.6rem,12vw,5rem)] font-black uppercase leading-[0.86] tracking-[-0.08em] text-[#fff7f2]">Make every bite count.</h1><p className="mt-6 max-w-[430px] text-[0.98rem] leading-7 text-[#bdb2ac]">Sign in to save your bag, keep delivery details, and track every order from the kitchen to your door.</p>{import.meta.env.DEV ? <form onSubmit={(event) => { event.preventDefault(); demoLoginMutation.mutate({ username, password }); }} className="mt-8 max-w-[420px] rounded-[15px] border border-[#48413e] bg-[#242424] p-5 shadow-[3px_3px_0_#050505]"><p className="text-[10px] font-black uppercase tracking-[0.15em] text-[#ff5a1f]">Development demo sign-in</p><p className="mt-2 text-xs leading-5 text-[#bdb2ac]">Local-only credentials are prefilled for this preview. This entry point is disabled in production.</p><label className="mt-4 block text-[10px] font-black uppercase tracking-[0.12em] text-[#cfc2bb]">Username<input value={username} onChange={(event) => setUsername(event.target.value)} type="email" className="mt-2 h-11 w-full rounded-[9px] border border-[#4a403c] bg-[#171717] px-3 text-sm font-normal normal-case tracking-normal text-[#fff7f2] outline-none focus:border-[#ff5a1f]" /></label><label className="mt-4 block text-[10px] font-black uppercase tracking-[0.12em] text-[#cfc2bb]">Password<input value={password} onChange={(event) => setPassword(event.target.value)} type="password" className="mt-2 h-11 w-full rounded-[9px] border border-[#4a403c] bg-[#171717] px-3 text-sm font-normal normal-case tracking-normal text-[#fff7f2] outline-none focus:border-[#ff5a1f]" /></label><button type="submit" disabled={demoLoginMutation.isPending} className="mt-5 inline-flex h-12 items-center gap-3 rounded-[10px] bg-[#ff5a1f] px-5 text-xs font-black uppercase tracking-[0.16em] text-[#111111] shadow-[4px_4px_0_#000] disabled:opacity-60"><LogIn size={17} /> {demoLoginMutation.isPending ? "Signing in…" : "Use demo account"}</button></form> : <button type="button" onClick={() => startLogin()} className="mt-8 inline-flex h-12 items-center gap-3 rounded-[10px] bg-[#ff5a1f] px-5 text-xs font-black uppercase tracking-[0.16em] text-[#111111] shadow-[4px_4px_0_#000] transition-all active:translate-y-0.5"><LogIn size={17} /> Sign in</button>}</div></div>;

  return <div className="min-h-screen bg-[#0b0b0b] px-5 py-10 pb-28 sm:px-8 md:px-12 md:py-14"><div className="mx-auto max-w-[780px]"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[0.18em] text-[#ff5a1f]">Your account</p><h1 className="mt-2 font-display text-[clamp(2.4rem,10vw,4rem)] font-black uppercase leading-none tracking-[-0.08em] text-[#fff7f2]">{user?.name || "Crunch crew"}</h1><p className="mt-3 text-sm text-[#bdb2ac]">{user?.email || "Signed in customer"}</p></div><button type="button" onClick={() => logout().then(() => toast.success("Signed out"))} className="flex h-10 items-center gap-2 rounded-[10px] border border-[#4a403c] px-3 text-[10px] font-black uppercase tracking-[0.12em] text-[#cfc2bb] transition-colors hover:border-[#ff5a1f] hover:text-[#ff5a1f]"><LogOut size={15} /> Sign out</button></div>

  <section className="mt-8 rounded-[15px] border border-[#48413e] bg-[#242424] p-5 shadow-[3px_3px_0_#050505]"><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-[10px] bg-[#ff5a1f] text-[#111111]"><ChefHat size={19} /></span><div className="min-w-0 flex-1"><p className="text-[10px] font-black uppercase tracking-[0.15em] text-[#ff5a1f]">Staff tools</p><h2 className="mt-1 font-display text-[1.2rem] font-black uppercase tracking-[-0.04em] text-[#fff7f2]">Kitchen Board</h2><p className="mt-2 text-sm leading-6 text-[#bdb2ac]">{kitchenAccess.description}</p>{kitchenAccess.canUseKitchen ? <button type="button" onClick={() => setLocation("/kitchen")} className="mt-4 inline-flex h-10 items-center gap-2 rounded-[9px] bg-[#ff5a1f] px-4 text-[10px] font-black uppercase tracking-[0.13em] text-[#17100d] shadow-[3px_3px_0_#080808] transition-all active:translate-y-0.5"><ChefHat size={15} /> Open Kitchen Board <ArrowRight size={15} /></button> : <p className="mt-4 text-[11px] font-bold uppercase tracking-[0.1em] text-[#8f847d]">{kitchenAccess.guidance}</p>}</div></div></section>

  <section className="mt-8 rounded-[15px] border border-[#48413e] bg-[#242424] p-5 shadow-[3px_3px_0_#050505]"><div className="flex items-center gap-2"><MapPin size={17} className="text-[#ff5a1f]" /><h2 className="font-display text-[1.1rem] font-black uppercase tracking-[-0.03em] text-[#fff7f2]">Delivery details</h2></div><div className="mt-5 grid gap-4"><label className="text-[10px] font-black uppercase tracking-[0.13em] text-[#bdb2ac]">Phone<input value={phone} onChange={(event) => setPhone(event.target.value)} placeholder="e.g. 024 000 0000" className="mt-2 h-11 w-full rounded-[9px] border border-[#4a403c] bg-[#171717] px-3 text-sm font-normal normal-case tracking-normal text-[#fff7f2] outline-none transition-colors focus:border-[#ff5a1f]" /></label><label className="text-[10px] font-black uppercase tracking-[0.13em] text-[#bdb2ac]">Default delivery address<textarea value={defaultAddress} onChange={(event) => setDefaultAddress(event.target.value)} placeholder="Add your delivery address" rows={3} className="mt-2 w-full rounded-[9px] border border-[#4a403c] bg-[#171717] px-3 py-2.5 text-sm font-normal normal-case tracking-normal text-[#fff7f2] outline-none transition-colors focus:border-[#ff5a1f]" /></label><button type="button" disabled={saveMutation.isPending} onClick={() => saveMutation.mutate({ phone, defaultAddress })} className="flex h-11 items-center justify-center gap-2 rounded-[10px] bg-[#ff5a1f] text-xs font-black uppercase tracking-[0.14em] text-[#111111] shadow-[3px_3px_0_#050505] disabled:opacity-60"><Save size={16} /> {saveMutation.isPending ? "Saving…" : "Save details"}</button></div></section>

  <section className="mt-8"><div className="flex items-center gap-2"><PackageCheck size={17} className="text-[#ff5a1f]" /><h2 className="font-display text-[1.15rem] font-black uppercase tracking-[-0.03em] text-[#fff7f2]">Order history</h2></div>{ordersQuery.isLoading ? <div className="mt-4 h-28 animate-pulse rounded-[15px] bg-[#242424]" /> : (ordersQuery.data?.length ?? 0) === 0 ? <div className="mt-4 rounded-[15px] border border-[#393432] bg-[#242424] p-6 text-sm leading-6 text-[#bdb2ac]">Your order history will appear here once you place your first Crunch Bite order.</div> : <div className="mt-4 space-y-3">{ordersQuery.data?.map((order) => <article key={order.id} className="flex items-center justify-between gap-4 rounded-[15px] border border-[#48413e] bg-[#242424] p-4 shadow-[3px_3px_0_#050505]"><div><p className="font-display text-base font-black text-[#fff7f2]">{order.orderNumber}</p><p className="mt-1 text-xs text-[#bdb2ac]">{new Date(order.createdAt).toLocaleDateString("en-GH", { day: "numeric", month: "short", year: "numeric" })}</p></div><div className="text-right"><p className="text-[10px] font-black uppercase tracking-[0.12em] text-[#ff5a1f]">{order.status}</p><p className="mt-1 font-display font-black text-[#fff7f2]">{formatGhsPesewas(order.totalPesewas)}</p></div></article>)}</div>}</section></div></div>;
}
