import { ArrowRight, ChefHat, CircleDollarSign, Clock3, CreditCard, LayoutDashboard, PackageOpen, ReceiptText, ShieldAlert, ShoppingBag, TrendingUp, Users, WalletCards } from "lucide-react";
import { useAuth } from "@/_core/hooks/useAuth";
import DashboardLayout from "@/components/DashboardLayout";
import { trpc } from "@/lib/trpc";
import { formatGhsPesewas } from "@/lib/catalog-types";

const labelize = (value?: string | null) => (value ?? "not recorded").replaceAll("_", " ");
type Tone = "orange" | "mint" | "violet" | "gold" | "red" | "neutral";

function Pill({ children, tone = "neutral" }: { children: React.ReactNode; tone?: Tone }) {
  const tones: Record<Tone, string> = { neutral: "border-[#4b4541] bg-[#302c29] text-[#ded3cc]", orange: "border-[#ff5a1f]/40 bg-[#ff5a1f]/10 text-[#ff966f]", mint: "border-[#9de3ca]/35 bg-[#9de3ca]/10 text-[#aeeed7]", violet: "border-[#b6a5ff]/35 bg-[#b6a5ff]/10 text-[#d2c7ff]", gold: "border-[#ffd36f]/35 bg-[#ffd36f]/10 text-[#ffe19a]", red: "border-[#ff8a8a]/35 bg-[#ff5656]/10 text-[#ffb0b0]" };
  return <span className={`rounded-full border px-2 py-1 text-[9px] font-black uppercase tracking-[0.1em] ${tones[tone]}`}>{children}</span>;
}

function Card({ icon, label, value, detail, tone = "orange" }: { icon: React.ReactNode; label: string; value: string | number; detail: string; tone?: Exclude<Tone, "red" | "neutral"> }) {
  const colors = { orange: "bg-[#ff5a1f] text-[#1b100c]", mint: "bg-[#9de3ca] text-[#0f211b]", violet: "bg-[#b6a5ff] text-[#1d183b]", gold: "bg-[#ffd36f] text-[#2d2107]" };
  return <article className="rounded-[18px] border border-[#45403c] bg-[#242424] p-4 shadow-[4px_4px_0_#080808]"><span className={`flex h-9 w-9 items-center justify-center rounded-[11px] ${colors[tone]}`}>{icon}</span><p className="mt-5 text-[9px] font-black uppercase tracking-[0.14em] text-[#a89d96]">{label}</p><p className="mt-2 font-display text-2xl font-black tracking-[-0.055em] text-[#fff7f2]">{value}</p><p className="mt-2 text-xs leading-5 text-[#bdb2ac]">{detail}</p></article>;
}

function PanelTitle({ eyebrow, title, children }: { eyebrow: string; title: string; children?: React.ReactNode }) {
  return <div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[0.16em] text-[#ff7441]">{eyebrow}</p><h2 className="mt-2 font-display text-2xl font-black uppercase tracking-[-0.055em] text-[#fff7f2]">{title}</h2></div>{children}</div>;
}

function Empty({ icon, message }: { icon: React.ReactNode; message: string }) {
  return <div className="mt-5 flex min-h-32 flex-col items-center justify-center rounded-[14px] border border-dashed border-[#4a403c] bg-[#191817] p-5 text-center"><span className="text-[#ff7441]">{icon}</span><p className="mt-3 max-w-sm text-sm leading-6 text-[#bdb2ac]">{message}</p></div>;
}

export default function AdminDashboard() {
  const { user, loading } = useAuth();
  const isAdmin = user?.role === "admin";
  const report = trpc.admin.console.useQuery(undefined, { enabled: isAdmin, retry: false, staleTime: 15_000, refetchInterval: 30_000, refetchOnWindowFocus: true });
  if (loading) return <div className="min-h-screen bg-[#111]" />;
  if (!isAdmin) return <div className="relative min-h-screen overflow-hidden bg-[#111] px-6 py-20 text-[#fff7f2]"><div className="pointer-events-none absolute -right-24 -top-24 h-72 w-72 rounded-full bg-[#ff5a1f]/10 blur-3xl" /><div className="relative mx-auto max-w-md overflow-hidden rounded-[18px] border border-[#4a403c] bg-[#242424] p-7 shadow-[5px_5px_0_#080808]"><div className="absolute inset-x-0 top-0 h-1 bg-[#ff5a1f]" /><p className="text-[10px] font-black uppercase tracking-[0.2em] text-[#ff7441]">The Crunch Bite · back of house</p><span className="mt-6 flex h-11 w-11 items-center justify-center rounded-[11px] bg-[#ff5a1f] text-[#17100d]"><ShieldAlert size={21} /></span><h1 className="mt-5 font-display text-3xl font-black uppercase leading-[0.9] tracking-[-0.065em]">Management<br />locked.</h1><p className="mt-4 text-sm leading-6 text-[#c4b9b2]">Sign in as the restaurant owner or manager to open sales, food performance, kitchen flow, and payment controls.</p></div></div>;

  const data = report.data;
  const maxRevenue = Math.max(1, ...(data?.dailySales.map((day) => day.revenuePesewas) ?? []));
  const refreshedAt = report.dataUpdatedAt ? new Date(report.dataUpdatedAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) : "—";
  const statusTone = (status?: string | null): Tone => status === "successful" || status === "completed" || status === "delivered" ? "mint" : status === "pending" || status === "accepted" || status === "preparing" || status === "ready" || status === "out_for_delivery" ? "orange" : status === "cancelled" || status === "failed" || status === "refunded" ? "red" : "neutral";

  return <DashboardLayout title="Manager Console" workspaceLabel="Owner / manager workspace" sidebarEyebrow="Management" statusLabel="Live reporting" menuItems={[{ icon: LayoutDashboard, label: "Manager Console", path: "/admin" }, { icon: ChefHat, label: "Kitchen board", path: "/kitchen" }, { icon: Users, label: "Customer profile", path: "/profile" }]}>
    <div className="min-h-screen bg-[#111] text-[#fff7f2]"><div className="mx-auto max-w-[1360px] px-4 py-6 sm:px-6 lg:px-8">
      <section className="relative overflow-hidden rounded-[24px] border border-[#655047] bg-[#24201f] px-5 py-6 shadow-[5px_5px_0_#080808] sm:px-7 sm:py-8"><div className="pointer-events-none absolute -right-12 -top-20 h-56 w-56 rounded-full bg-[#ff5a1f]/15 blur-3xl" /><div className="relative flex flex-col gap-6 xl:flex-row xl:items-end xl:justify-between"><div className="max-w-2xl"><p className="text-[10px] font-black uppercase tracking-[0.2em] text-[#ff7441]">The Crunch Bite · Owner view</p><h1 className="mt-3 font-display text-[clamp(2.5rem,7vw,5rem)] font-black uppercase leading-[0.86] tracking-[-0.085em]">Manager<br /><span className="text-[#ffb08f]">Console.</span></h1><p className="mt-5 max-w-xl text-sm leading-6 text-[#c9beb7]">Your live view of food performance, fulfillment flow, and payment status. Financial metrics represent recorded sales and collection state, not profit.</p></div><div className="flex flex-wrap items-center gap-3"><div className="rounded-[14px] border border-[#51443e] bg-[#171514]/80 px-4 py-3"><p className="text-[9px] font-black uppercase tracking-[0.13em] text-[#a89d96]">Snapshot refreshed</p><p className="mt-1 flex items-center gap-2 text-sm font-bold"><Clock3 size={14} className="text-[#ff7441]" />{refreshedAt}</p></div><a href="/kitchen" className="inline-flex items-center gap-2 rounded-[12px] bg-[#ff5a1f] px-4 py-3 text-[10px] font-black uppercase tracking-[0.11em] text-[#20110b] transition-transform hover:bg-[#ff7141] active:scale-[0.97]">Open Kitchen <ArrowRight size={15} /></a></div></div></section>

      {report.isLoading ? <Loading /> : report.isError || !data ? <div className="mt-6 rounded-[18px] border border-red-400/30 bg-red-400/10 p-5 text-sm text-red-200">Manager data could not be loaded. Refresh this page to try again.</div> : <>
        <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Card icon={<CircleDollarSign size={18} />} label="Fulfilled sales" value={formatGhsPesewas(data.summary.fulfilledSalesPesewas)} detail={`${data.summary.fulfilledOrders} completed / delivered orders`} /><Card icon={<CreditCard size={18} />} label="Online received" value={formatGhsPesewas(data.finance.onlineCollectedPesewas)} detail="Verified Card and Mobile Money" tone="mint" /><Card icon={<WalletCards size={18} />} label="Cash to reconcile" value={formatGhsPesewas(data.finance.cashFulfilledToReconcilePesewas)} detail={`${data.finance.cashFulfilledToReconcileCount} finished cash orders`} tone="gold" /><Card icon={<ChefHat size={18} />} label="Active kitchen" value={data.summary.activeOrders} detail={`${data.summary.todayOrders} orders created today`} tone="violet" /><Card icon={<PackageOpen size={18} />} label="Menu health" value={`${data.summary.activeProducts} live`} detail={`${data.summary.inactiveProducts} currently hidden`} /></section>

        <section className="mt-6 grid gap-5 xl:grid-cols-[1.25fr_0.75fr]"><article className="rounded-[20px] border border-[#45403c] bg-[#242424] p-5 shadow-[4px_4px_0_#080808] sm:p-6"><PanelTitle eyebrow="Sales flow" title="Fulfilled revenue trend"><Pill tone="mint">Last 7 days</Pill></PanelTitle>{data.dailySales.length ? <div className="mt-8 flex h-52 items-end gap-2 sm:gap-4">{data.dailySales.map((day) => <div key={day.day} className="group flex h-full min-w-0 flex-1 flex-col justify-end"><p className="mb-2 truncate text-center text-[10px] font-black text-[#d9cdc6] sm:opacity-100">{formatGhsPesewas(day.revenuePesewas)}</p><div className="min-h-[8px] rounded-t-[10px] bg-[#ff5a1f] transition-colors group-hover:bg-[#ff8051]" style={{ height: `${Math.max(8, Math.round(day.revenuePesewas / maxRevenue * 100))}%` }} /><p className="mt-3 truncate text-center text-[9px] font-black uppercase tracking-[0.08em] text-[#a89d96]">{day.day}</p><p className="mt-1 text-center text-[10px] text-[#c8bbb4]">{day.orderCount} orders</p></div>)}</div> : <Empty icon={<TrendingUp size={20} />} message="Fulfilled revenue appears after completed or delivered orders." />}<div className="mt-6 flex flex-wrap gap-4 border-t border-[#403936] pt-5"><Stat label="Today fulfilled" value={formatGhsPesewas(data.summary.todayFulfilledSalesPesewas)} /><Stat label="Customers" value={data.summary.customerCount} /><Stat label="Cancelled" value={data.summary.cancelledOrders} /></div></article>
          <article className="rounded-[20px] border border-[#45403c] bg-[#242424] p-5 shadow-[4px_4px_0_#080808] sm:p-6"><PanelTitle eyebrow="Attention queue" title="Manager follow-ups" /><div className="mt-5 space-y-3"><FollowUp icon={<ChefHat size={16} />} label="Kitchen work in progress" value={`${data.summary.activeOrders} active`} tone="orange" /><FollowUp icon={<Clock3 size={16} />} label="Pending online payments" value={`${data.finance.pendingOnlineCount} · ${formatGhsPesewas(data.finance.pendingOnlinePesewas)}`} tone={data.finance.pendingOnlineCount ? "gold" : "mint"} /><FollowUp icon={<ReceiptText size={16} />} label="Failed or refunded online" value={`${data.finance.failedOrRefundedOnlineCount} · ${formatGhsPesewas(data.finance.failedOrRefundedOnlinePesewas)}`} tone={data.finance.failedOrRefundedOnlineCount ? "red" : "mint"} /><FollowUp icon={<WalletCards size={16} />} label="Completed cash orders" value={`${data.finance.cashFulfilledToReconcileCount} to reconcile`} tone="gold" /></div><div className="mt-5 rounded-[12px] border border-[#ffd36f]/20 bg-[#ffd36f]/5 p-3 text-xs leading-5 text-[#e8d8a0]"><b>Finance note.</b> Cash is shown for reconciliation. Online revenue is counted only after successful payment verification.</div></article></section>

        <section className="mt-6 grid gap-5 xl:grid-cols-[0.85fr_1.15fr]"><article className="rounded-[20px] border border-[#45403c] bg-[#242424] p-5 shadow-[4px_4px_0_#080808] sm:p-6"><div className="flex items-start justify-between gap-3"><PanelTitle eyebrow="Food performance" title="Top selling dishes" /><a href="/kitchen" className="shrink-0 rounded-[10px] border border-[#ff5a1f]/35 px-3 py-2 text-[9px] font-black uppercase tracking-[0.1em] text-[#ff9a74] hover:bg-[#ff5a1f]/10">Manage menu</a></div>{data.topItems.length ? <ol className="mt-5 space-y-2">{data.topItems.map((item, index) => <li key={item.name} className="grid grid-cols-[26px_minmax(0,1fr)_auto] items-center gap-3 rounded-[12px] bg-[#191817] px-3 py-3"><span className="font-display text-lg font-black text-[#ff7441]">{index + 1}</span><div className="min-w-0"><p className="truncate text-sm font-bold">{item.name}</p><p className="mt-1 text-[10px] text-[#a89d96]">{item.quantity} sold · {item.orderCount} orders</p></div><p className="text-right text-xs font-black text-[#ffd36f]">{formatGhsPesewas(item.revenuePesewas)}</p></li>)}</ol> : <Empty icon={<ShoppingBag size={20} />} message="Food performance will appear when fulfilled orders have line items." />}<p className="mt-5 text-[11px] leading-5 text-[#a89d96]">Ranking uses the preserved menu and price snapshots from fulfilled orders.</p></article>
          <article className="rounded-[20px] border border-[#45403c] bg-[#242424] p-5 shadow-[4px_4px_0_#080808] sm:p-6"><PanelTitle eyebrow="Payment ledger" title="Payment method & status" />{data.paymentBreakdown.length ? <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[500px] border-separate border-spacing-y-2 text-left"><thead><tr className="text-[9px] font-black uppercase tracking-[0.12em] text-[#a89d96]"><th>Method</th><th>Status</th><th className="text-right">Orders</th><th className="text-right">Recorded amount</th></tr></thead><tbody>{data.paymentBreakdown.map((row) => <tr key={`${row.method}-${row.status}`} className="bg-[#191817] text-sm"><td className="rounded-l-[10px] px-3 py-3 font-bold">{labelize(row.method)}</td><td className="px-3 py-3"><Pill tone={statusTone(row.status)}>{row.status}</Pill></td><td className="px-3 py-3 text-right text-[#c9beb7]">{row.orderCount}</td><td className="rounded-r-[10px] px-3 py-3 text-right font-black text-[#ffd36f]">{formatGhsPesewas(row.amountPesewas)}</td></tr>)}</tbody></table></div> : <Empty icon={<CreditCard size={20} />} message="Payment records will appear after the first order." />}<p className="mt-5 text-[11px] leading-5 text-[#a89d96]">This payment-status ledger excludes ingredient costs, supplier bills, wages, and cash deposits.</p></article></section>

        <section className="mt-6 rounded-[20px] border border-[#45403c] bg-[#242424] p-5 shadow-[4px_4px_0_#080808] sm:p-6"><PanelTitle eyebrow="Order oversight" title="Latest orders"><Pill>{data.recentOrders.length} recorded</Pill></PanelTitle>{data.recentOrders.length ? <div className="mt-5 grid gap-3 lg:grid-cols-2">{data.recentOrders.slice(0, 10).map((order) => <article key={order.id} className="rounded-[14px] border border-[#403936] bg-[#191817] p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="font-display text-base font-black">{order.orderNumber}</p><p className="mt-1 truncate text-xs text-[#bdb2ac]">{order.customerName || "Customer"} · {labelize(order.orderType)}</p></div><p className="shrink-0 font-display text-lg font-black text-[#ffd36f]">{formatGhsPesewas(order.totalPesewas)}</p></div><div className="mt-4 flex flex-wrap gap-2"><Pill tone={statusTone(order.status)}>{labelize(order.status)}</Pill><Pill>{labelize(order.paymentMethod)}</Pill><Pill tone={statusTone(order.paymentStatus)}>{order.paymentStatus ?? "pending"}</Pill></div></article>)}</div> : <Empty icon={<ReceiptText size={20} />} message="New restaurant orders will appear here." />}</section>
        <section className="mt-6 rounded-[18px] border border-[#4e4741] bg-[#1a1917] px-5 py-4 text-sm leading-6 text-[#c9beb7]"><b className="text-[#ffb08f]">Clear financial boundary:</b> Sandsly does not yet store profit, ingredient stock, supplier bills, payroll, or cash deposits. This console distinguishes fulfilled sales, verified online collections, and cash requiring reconciliation instead of estimating profit.</section>
      </>}
    </div></div>
  </DashboardLayout>;
}

function Stat({ label, value }: { label: string; value: string | number }) { return <div><p className="text-[9px] font-black uppercase tracking-[0.12em] text-[#a89d96]">{label}</p><p className="mt-1 font-display text-xl font-black">{value}</p></div>; }
function FollowUp({ icon, label, value, tone }: { icon: React.ReactNode; label: string; value: string; tone: Exclude<Tone, "violet" | "neutral"> }) { const c = { orange: "bg-[#ff5a1f]/13 text-[#ff9a74]", mint: "bg-[#9de3ca]/12 text-[#aeeed7]", red: "bg-[#ff5656]/12 text-[#ffb0b0]", gold: "bg-[#ffd36f]/12 text-[#ffe19a]" }; return <div className="flex items-center gap-3 rounded-[12px] border border-[#403936] bg-[#191817] p-3"><span className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-[9px] ${c[tone]}`}>{icon}</span><p className="min-w-0 flex-1 text-xs font-bold">{label}</p><p className="text-right text-[10px] font-black uppercase tracking-[0.06em] text-[#d8cbc4]">{value}</p></div>; }
function Loading() { return <div className="mt-6 animate-pulse space-y-6"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[1, 2, 3, 4, 5].map((item) => <div key={item} className="h-40 rounded-[18px] bg-[#242424]" />)}</div><div className="grid gap-5 xl:grid-cols-2"><div className="h-72 rounded-[20px] bg-[#242424]" /><div className="h-72 rounded-[20px] bg-[#242424]" /></div></div>; }
